version: '2'

services:
  item-app:
    image: ghcr.io/janwtr/a433-microservices/item-app:v1 
    depends_on:
      - item-db
    ports:
      - "80:8080"  # Asumsi bahwa item-app menjalankan server pada port 8080
    environment:
      DB_HOST: item-db  # Menentukan host database
    restart: always

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always

volumes:
  app-db:
